version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: aitor
      MYSQL_DATABASE: aitor
      MYSQL_USER: aitor
      MYSQL_PASSWORD: aitor
    volumes:
      - mysql_data:/var/lib/mysql  # Volumen persistente para los datos de la DB
      - ./db:/docker-entrypoint-initdb.d  # Montamos el script de inicialización
    networks:
      - webnet

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - .:/usr/share/nginx/html  # Compartir los archivos de la web con PHP-FPM
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-web
    ports:
      - "80:80"  # Redirigir puerto 80 del contenedor al 8080 de la máquina local
    volumes:
      - .:/usr/share/nginx/html  # Compartir los archivos de la web con Nginx
    networks:
      - webnet
    depends_on:
      - php  # Asegura que PHP-FPM se inicie antes que Nginx

volumes:
  mysql_data:

networks:
  webnet:
    driver: bridge
